services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      - PANGOLIN_ENDPOINT
      - DOCKER_SOCKET=/run/docker.sock
      - DOCKER_ENFORCE_NETWORK_VALIDATION=true
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
    secrets:
      - NEWT_ID.env
      - NEWT_SECRET.env
      - source: secrets2env.sh
        target: /run/secrets/secrets2env.sh
        mode: 0777
    entrypoint: ["/run/secrets/secrets2env.sh", "/app/newt"]

  auth:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    image: local/keycloak:26.3-providers
    container_name: auth
    env_file:
      - config.env
    environment:
      - KEYCLOAK_ADMIN
      - KC_PROXY=edge
      - KC_HOSTNAME=https://auth.${DOMAIN}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_DB
      - KC_DB_USERNAME
      - KC_DB_URL
    restart: unless-stopped
    labels:
      - "pangolin.proxy-resources.auth.name=Keycloak"
      - "pangolin.proxy-resources.auth.protocol=http"
      - "pangolin.proxy-resources.auth.full-domain=auth.${DOMAIN}"
      - "pangolin.proxy-resources.auth.targets[0].enabled=true"
      - "pangolin.proxy-resources.auth.targets[0].port=8080"
    secrets:
      - KEYCLOAK_ADMIN_PASSWORD.env
      - KC_DB_PASSWORD.env
      - source: secrets2env.sh
        target: /run/secrets/secrets2env.sh
        mode: 0777
    entrypoint: ["/run/secrets/secrets2env.sh", "/opt/keycloak/bin/kc.sh"]
    command: ["start"]
    volumes:
      - keycloak-data:/opt/keycloak/data
    depends_on:
      db:
        condition: service_started

  db:
    image: mariadb:11.4
    container_name: keycloak-db
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      - MARIADB_DATABASE=keycloak
      - MARIADB_USER=${KC_DB_USERNAME}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    volumes:
      - keycloak-mariadb:/var/lib/mysql
    secrets:
      - db_password
      - mariadb_root_password

volumes:
  keycloak-data:
  keycloak-mariadb:

secrets:
  KEYCLOAK_ADMIN_PASSWORD.env:
    file: ./secrets/KEYCLOAK_ADMIN_PASSWORD.env
  KC_DB_PASSWORD.env:
    file: ./secrets/DB_PASSWORD.env
  db_password:
    file: ./secrets/DB_PASSWORD.env
  mariadb_root_password:
    file: ./secrets/MARIADB_ROOT_PASSWORD
  NEWT_ID.env:
    file: ./secrets/NEWT_ID.env
  NEWT_SECRET.env:
    file: ./secrets/NEWT_SECRET.env
  secrets2env.sh:
    file: ./secrets2env.sh
