model_list:
  - model_name: bedrock-claude-opus-4-1
    litellm_params:
      model: bedrock/us.anthropic.claude-opus-4-1-20250805-v1:0
      aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-claude-sonnet-4
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_region_name: os.environ/AWS_REGION_NAME

  # OpenAI (direct)
  - model_name: openai-gpt-5-2025-08-07
    litellm_params:
      model: openai/gpt-5-2025-08-07
      api_key: os.environ/OPENAI_API_KEY
      reasoning_effort: high

  # Anthropic (direct)
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
      api_key: os.environ/ANTHROPIC_API_KEY
      thinking: {
        "type": "enabled",
        "budget_tokens": 1024
      }

  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
      thinking: {
        "type": "enabled",
        "budget_tokens": 1024
      }

general_settings:
  # master_key provided via env: LITELLM_MASTER_KEY
  # database_url provided via env: DATABASE_URL
