entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  cf:
    acme:
      email: ${ACME_EMAIL}
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
